import "server-only";

import { getInternalNotificationSettings } from "@/services/site-settings/site-settings.service";
import { sendSmtpEmail } from "@/services/email/smtp.service";

function escapeHtml(value) {
  return String(value || "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function getSiteBaseUrl() {
  const configuredUrl =
    process.env.NEXT_PUBLIC_SITE_URL ||
    process.env.SITE_URL ||
    process.env.VERCEL_PROJECT_PRODUCTION_URL ||
    process.env.VERCEL_URL ||
    "";

  if (!configuredUrl) {
    return "";
  }

  const normalizedUrl =
    configuredUrl.startsWith("http://") || configuredUrl.startsWith("https://")
      ? configuredUrl
      : `https://${configuredUrl}`;

  return normalizedUrl.replace(/\/+$/, "");
}

export function getAdminLoginUrl() {
  const siteBaseUrl = getSiteBaseUrl();

  if (!siteBaseUrl) {
    return "";
  }

  return `${siteBaseUrl}/admin/login`;
}

function getEnglishContent({ displayName, resetLink, isNewUser }) {
  const safeName = displayName || "Administrator";

  return {
    subject: isNewUser
      ? "Set up your HCS Thailand administrator account"
      : "Reset your HCS Thailand administrator password",

    text: [
      `Hello ${safeName},`,
      "",

      isNewUser
        ? "An administrator account has been created for you on the HCS Thailand website."
        : "A password reset was requested for your HCS Thailand administrator account.",

      "",
      isNewUser
        ? "Use the secure link below to create your password:"
        : "Use the secure link below to set a new password:",

      "",
      resetLink,
      "",
      "This link is generated securely by Firebase Authentication and can only be used for a limited time.",
      "",
      "If you did not expect this email, please contact your system administrator.",
      "",
      "HCS Thailand",
    ].join("\n"),

    html: `
      <div style="font-family:Arial,sans-serif;max-width:640px;margin:0 auto;color:#0f2740">
        <div style="background:#0979c4;padding:22px 26px;color:#ffffff">
          <strong style="font-size:21px">
            HCS Thailand
          </strong>
        </div>

        <div style="border:1px solid #dbe5ee;border-top:0;padding:28px">
          <h1 style="font-size:22px;line-height:1.35;margin:0 0 16px">
            ${
              isNewUser
                ? "Set up your administrator account"
                : "Reset your administrator password"
            }
          </h1>

          <p style="line-height:1.7;margin:0 0 14px">
            Hello ${escapeHtml(safeName)},
          </p>

          <p style="line-height:1.7;margin:0 0 20px">
            ${
              isNewUser
                ? "An administrator account has been created for you on the HCS Thailand website."
                : "A password reset was requested for your HCS Thailand administrator account."
            }
          </p>

          <p style="margin:24px 0">
            <a
              href="${escapeHtml(resetLink)}"
              style="display:inline-block;background:#0979c4;color:#ffffff;text-decoration:none;font-weight:700;padding:13px 22px;border-radius:8px"
            >
              ${isNewUser ? "Create password" : "Reset password"}
            </a>
          </p>

          <p style="font-size:13px;line-height:1.6;color:#64748b;margin:20px 0 0">
            This secure link is generated by Firebase Authentication and can only be used for a limited time.
          </p>

          <p style="font-size:13px;line-height:1.6;color:#64748b;margin:12px 0 0">
            If you did not expect this email, please contact your system administrator.
          </p>
        </div>
      </div>
    `,
  };
}

function getThaiContent({ displayName, resetLink, isNewUser }) {
  const safeName = displayName || "ผู้ดูแลระบบ";

  return {
    subject: isNewUser
      ? "ตั้งค่าบัญชีผู้ดูแลระบบเว็บไซต์ HCS Thailand"
      : "ตั้งรหัสผ่านใหม่สำหรับเว็บไซต์ HCS Thailand",

    text: [
      `เรียน ${safeName}`,
      "",

      isNewUser
        ? "บัญชีผู้ดูแลระบบเว็บไซต์ HCS Thailand ของคุณถูกสร้างเรียบร้อยแล้ว"
        : "มีการขอตั้งรหัสผ่านใหม่สำหรับบัญชีผู้ดูแลระบบเว็บไซต์ HCS Thailand ของคุณ",

      "",
      isNewUser
        ? "กรุณาใช้ลิงก์ที่ปลอดภัยด้านล่างเพื่อตั้งรหัสผ่าน:"
        : "กรุณาใช้ลิงก์ที่ปลอดภัยด้านล่างเพื่อตั้งรหัสผ่านใหม่:",

      "",
      resetLink,
      "",
      "ลิงก์นี้สร้างโดย Firebase Authentication และสามารถใช้งานได้ภายในระยะเวลาที่กำหนดเท่านั้น",
      "",
      "หากคุณไม่ได้คาดว่าจะได้รับอีเมลนี้ กรุณาติดต่อผู้ดูแลระบบ",
      "",
      "HCS Thailand",
    ].join("\n"),

    html: `
      <div style="font-family:Arial,'Noto Sans Thai',sans-serif;max-width:640px;margin:0 auto;color:#0f2740">
        <div style="background:#0979c4;padding:22px 26px;color:#ffffff">
          <strong style="font-size:21px">
            HCS Thailand
          </strong>
        </div>

        <div style="border:1px solid #dbe5ee;border-top:0;padding:28px">
          <h1 style="font-size:22px;line-height:1.45;margin:0 0 16px">
            ${isNewUser ? "ตั้งค่าบัญชีผู้ดูแลระบบ" : "ตั้งรหัสผ่านใหม่"}
          </h1>

          <p style="line-height:1.8;margin:0 0 14px">
            เรียน ${escapeHtml(safeName)}
          </p>

          <p style="line-height:1.8;margin:0 0 20px">
            ${
              isNewUser
                ? "บัญชีผู้ดูแลระบบเว็บไซต์ HCS Thailand ของคุณถูกสร้างเรียบร้อยแล้ว"
                : "มีการขอตั้งรหัสผ่านใหม่สำหรับบัญชีผู้ดูแลระบบเว็บไซต์ HCS Thailand ของคุณ"
            }
          </p>

          <p style="margin:24px 0">
            <a
              href="${escapeHtml(resetLink)}"
              style="display:inline-block;background:#0979c4;color:#ffffff;text-decoration:none;font-weight:700;padding:13px 22px;border-radius:8px"
            >
              ${isNewUser ? "ตั้งรหัสผ่าน" : "ตั้งรหัสผ่านใหม่"}
            </a>
          </p>

          <p style="font-size:13px;line-height:1.8;color:#64748b;margin:20px 0 0">
            ลิงก์นี้สร้างโดย Firebase Authentication และสามารถใช้งานได้ภายในระยะเวลาที่กำหนดเท่านั้น
          </p>

          <p style="font-size:13px;line-height:1.8;color:#64748b;margin:12px 0 0">
            หากคุณไม่ได้คาดว่าจะได้รับอีเมลนี้ กรุณาติดต่อผู้ดูแลระบบ
          </p>
        </div>
      </div>
    `,
  };
}

function createPasswordEmailContent({
  displayName,
  preferredLocale,
  resetLink,
  isNewUser,
}) {
  if (preferredLocale === "th") {
    return getThaiContent({
      displayName,
      resetLink,
      isNewUser,
    });
  }

  return getEnglishContent({
    displayName,
    resetLink,
    isNewUser,
  });
}

async function getSmtpSettings() {
  const notificationSettings = await getInternalNotificationSettings();

  const emailSettings = notificationSettings.email;

  if (
    !emailSettings?.smtpHost ||
    !emailSettings?.smtpUsername ||
    !emailSettings?.smtpPasswordEncrypted ||
    !emailSettings?.fromEmail
  ) {
    throw new Error("SMTP settings are not configured completely");
  }

  return emailSettings;
}

export async function sendUserPasswordEmail({
  email,
  displayName,
  preferredLocale = "th",
  resetLink,
  isNewUser = false,
}) {
  const normalizedEmail = String(email || "")
    .trim()
    .toLowerCase();

  if (!normalizedEmail) {
    throw new Error("User email is required");
  }

  if (!resetLink) {
    throw new Error("Password reset link is required");
  }

  const settings = await getSmtpSettings();

  const content = createPasswordEmailContent({
    displayName,

    preferredLocale,

    resetLink,

    isNewUser,
  });

  return sendSmtpEmail({
    settings,

    to: [normalizedEmail],

    subject: content.subject,

    text: content.text,

    html: content.html,
  });
}
