export const ADMIN_ROLES = Object.freeze({
  SUPERADMIN: "superadmin",
  ADMIN: "admin",
  EDITOR: "editor",
});

export const USER_STATUSES = Object.freeze({
  ACTIVE: "active",
  SUSPENDED: "suspended",
  INVITED: "invited",
});

export const ADMIN_PERMISSIONS = Object.freeze({
  ALL: "*",

  DASHBOARD_VIEW: "dashboard.view",

  USERS_VIEW: "users.view",
  USERS_CREATE: "users.create",
  USERS_UPDATE: "users.update",
  USERS_DELETE: "users.delete",

  SITE_SETTINGS_VIEW: "siteSettings.view",
  SITE_SETTINGS_UPDATE: "siteSettings.update",

  PAGES_VIEW: "pages.view",
  PAGES_CREATE: "pages.create",
  PAGES_UPDATE: "pages.update",
  PAGES_DELETE: "pages.delete",
  PAGES_PUBLISH: "pages.publish",

  CATEGORIES_VIEW: "categories.view",
  CATEGORIES_CREATE: "categories.create",
  CATEGORIES_UPDATE: "categories.update",
  CATEGORIES_DELETE: "categories.delete",

  PRODUCTS_VIEW: "products.view",
  PRODUCTS_CREATE: "products.create",
  PRODUCTS_UPDATE: "products.update",
  PRODUCTS_DELETE: "products.delete",
  PRODUCTS_PUBLISH: "products.publish",

  SOLUTIONS_VIEW: "solutions.view",
  SOLUTIONS_CREATE: "solutions.create",
  SOLUTIONS_UPDATE: "solutions.update",
  SOLUTIONS_DELETE: "solutions.delete",
  SOLUTIONS_PUBLISH: "solutions.publish",

  PROJECTS_VIEW: "projects.view",
  PROJECTS_CREATE: "projects.create",
  PROJECTS_UPDATE: "projects.update",
  PROJECTS_DELETE: "projects.delete",
  PROJECTS_PUBLISH: "projects.publish",

  STANDARDS_VIEW: "standards.view",
  STANDARDS_CREATE: "standards.create",
  STANDARDS_UPDATE: "standards.update",
  STANDARDS_DELETE: "standards.delete",

  DOWNLOADS_VIEW: "downloads.view",
  DOWNLOADS_CREATE: "downloads.create",
  DOWNLOADS_UPDATE: "downloads.update",
  DOWNLOADS_DELETE: "downloads.delete",

  MEDIA_VIEW: "media.view",
  MEDIA_UPLOAD: "media.upload",
  MEDIA_UPDATE: "media.update",
  MEDIA_DELETE: "media.delete",

  MESSAGES_VIEW: "messages.view",
  MESSAGES_UPDATE: "messages.update",
  MESSAGES_DELETE: "messages.delete",

  AUDIT_LOGS_VIEW: "auditLogs.view",

  TRASH_VIEW: "trash.view",
  TRASH_RESTORE: "trash.restore",
  TRASH_DELETE_PERMANENTLY: "trash.deletePermanently",
});

export const ROLE_PERMISSIONS = Object.freeze({
  [ADMIN_ROLES.SUPERADMIN]: [ADMIN_PERMISSIONS.ALL],

  [ADMIN_ROLES.ADMIN]: [
    ADMIN_PERMISSIONS.DASHBOARD_VIEW,

    ADMIN_PERMISSIONS.USERS_VIEW,
    ADMIN_PERMISSIONS.USERS_CREATE,
    ADMIN_PERMISSIONS.USERS_UPDATE,

    ADMIN_PERMISSIONS.SITE_SETTINGS_VIEW,
    ADMIN_PERMISSIONS.SITE_SETTINGS_UPDATE,

    ADMIN_PERMISSIONS.PAGES_VIEW,
    ADMIN_PERMISSIONS.PAGES_CREATE,
    ADMIN_PERMISSIONS.PAGES_UPDATE,
    ADMIN_PERMISSIONS.PAGES_DELETE,
    ADMIN_PERMISSIONS.PAGES_PUBLISH,

    ADMIN_PERMISSIONS.CATEGORIES_VIEW,
    ADMIN_PERMISSIONS.CATEGORIES_CREATE,
    ADMIN_PERMISSIONS.CATEGORIES_UPDATE,
    ADMIN_PERMISSIONS.CATEGORIES_DELETE,

    ADMIN_PERMISSIONS.PRODUCTS_VIEW,
    ADMIN_PERMISSIONS.PRODUCTS_CREATE,
    ADMIN_PERMISSIONS.PRODUCTS_UPDATE,
    ADMIN_PERMISSIONS.PRODUCTS_DELETE,
    ADMIN_PERMISSIONS.PRODUCTS_PUBLISH,

    ADMIN_PERMISSIONS.SOLUTIONS_VIEW,
    ADMIN_PERMISSIONS.SOLUTIONS_CREATE,
    ADMIN_PERMISSIONS.SOLUTIONS_UPDATE,
    ADMIN_PERMISSIONS.SOLUTIONS_DELETE,
    ADMIN_PERMISSIONS.SOLUTIONS_PUBLISH,

    ADMIN_PERMISSIONS.PROJECTS_VIEW,
    ADMIN_PERMISSIONS.PROJECTS_CREATE,
    ADMIN_PERMISSIONS.PROJECTS_UPDATE,
    ADMIN_PERMISSIONS.PROJECTS_DELETE,
    ADMIN_PERMISSIONS.PROJECTS_PUBLISH,

    ADMIN_PERMISSIONS.STANDARDS_VIEW,
    ADMIN_PERMISSIONS.STANDARDS_CREATE,
    ADMIN_PERMISSIONS.STANDARDS_UPDATE,
    ADMIN_PERMISSIONS.STANDARDS_DELETE,

    ADMIN_PERMISSIONS.DOWNLOADS_VIEW,
    ADMIN_PERMISSIONS.DOWNLOADS_CREATE,
    ADMIN_PERMISSIONS.DOWNLOADS_UPDATE,
    ADMIN_PERMISSIONS.DOWNLOADS_DELETE,

    ADMIN_PERMISSIONS.MEDIA_VIEW,
    ADMIN_PERMISSIONS.MEDIA_UPLOAD,
    ADMIN_PERMISSIONS.MEDIA_UPDATE,
    ADMIN_PERMISSIONS.MEDIA_DELETE,

    ADMIN_PERMISSIONS.MESSAGES_VIEW,
    ADMIN_PERMISSIONS.MESSAGES_UPDATE,
    ADMIN_PERMISSIONS.MESSAGES_DELETE,

    ADMIN_PERMISSIONS.AUDIT_LOGS_VIEW,

    ADMIN_PERMISSIONS.TRASH_VIEW,
    ADMIN_PERMISSIONS.TRASH_RESTORE,
  ],

  [ADMIN_ROLES.EDITOR]: [
    ADMIN_PERMISSIONS.DASHBOARD_VIEW,

    ADMIN_PERMISSIONS.PAGES_VIEW,
    ADMIN_PERMISSIONS.PAGES_CREATE,
    ADMIN_PERMISSIONS.PAGES_UPDATE,

    ADMIN_PERMISSIONS.CATEGORIES_VIEW,

    ADMIN_PERMISSIONS.PRODUCTS_VIEW,
    ADMIN_PERMISSIONS.PRODUCTS_CREATE,
    ADMIN_PERMISSIONS.PRODUCTS_UPDATE,

    ADMIN_PERMISSIONS.SOLUTIONS_VIEW,
    ADMIN_PERMISSIONS.SOLUTIONS_CREATE,
    ADMIN_PERMISSIONS.SOLUTIONS_UPDATE,

    ADMIN_PERMISSIONS.PROJECTS_VIEW,
    ADMIN_PERMISSIONS.PROJECTS_CREATE,
    ADMIN_PERMISSIONS.PROJECTS_UPDATE,

    ADMIN_PERMISSIONS.STANDARDS_VIEW,

    ADMIN_PERMISSIONS.DOWNLOADS_VIEW,

    ADMIN_PERMISSIONS.MEDIA_VIEW,
    ADMIN_PERMISSIONS.MEDIA_UPLOAD,

    ADMIN_PERMISSIONS.MESSAGES_VIEW,
  ],
});

export function isAdminRole(role) {
  return Object.values(ADMIN_ROLES).includes(role);
}

export function getRolePermissions(role) {
  return ROLE_PERMISSIONS[role] || [];
}

export function hasPermission(userPermissions = [], requiredPermission) {
  return (
    userPermissions.includes(ADMIN_PERMISSIONS.ALL) ||
    userPermissions.includes(requiredPermission)
  );
}
