export const AUDIT_ACTIONS = Object.freeze({
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_LOGOUT: "AUTH_LOGOUT",

  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  USER_RESTORE: "USER_RESTORE",
  USER_PREFERENCE_UPDATE: "USER_PREFERENCE_UPDATE",

  SITE_SETTINGS_CREATE: "SITE_SETTINGS_CREATE",
  SITE_SETTINGS_UPDATE: "SITE_SETTINGS_UPDATE",

  PAGE_CREATE: "PAGE_CREATE",
  PAGE_UPDATE: "PAGE_UPDATE",
  PAGE_PUBLISH: "PAGE_PUBLISH",
  PAGE_UNPUBLISH: "PAGE_UNPUBLISH",
  PAGE_DELETE: "PAGE_DELETE",
  PAGE_RESTORE: "PAGE_RESTORE",

  CATEGORY_CREATE: "CATEGORY_CREATE",
  CATEGORY_UPDATE: "CATEGORY_UPDATE",
  CATEGORY_DELETE: "CATEGORY_DELETE",
  CATEGORY_RESTORE: "CATEGORY_RESTORE",

  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_PUBLISH: "PRODUCT_PUBLISH",
  PRODUCT_UNPUBLISH: "PRODUCT_UNPUBLISH",
  PRODUCT_DELETE: "PRODUCT_DELETE",
  PRODUCT_RESTORE: "PRODUCT_RESTORE",

  SOLUTION_CREATE: "SOLUTION_CREATE",
  SOLUTION_UPDATE: "SOLUTION_UPDATE",
  SOLUTION_PUBLISH: "SOLUTION_PUBLISH",
  SOLUTION_UNPUBLISH: "SOLUTION_UNPUBLISH",
  SOLUTION_DELETE: "SOLUTION_DELETE",
  SOLUTION_RESTORE: "SOLUTION_RESTORE",

  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_UPDATE: "PROJECT_UPDATE",
  PROJECT_PUBLISH: "PROJECT_PUBLISH",
  PROJECT_UNPUBLISH: "PROJECT_UNPUBLISH",
  PROJECT_DELETE: "PROJECT_DELETE",
  PROJECT_RESTORE: "PROJECT_RESTORE",

  STANDARD_CREATE: "STANDARD_CREATE",
  STANDARD_UPDATE: "STANDARD_UPDATE",
  STANDARD_DELETE: "STANDARD_DELETE",
  STANDARD_RESTORE: "STANDARD_RESTORE",

  DOWNLOAD_CREATE: "DOWNLOAD_CREATE",
  DOWNLOAD_UPDATE: "DOWNLOAD_UPDATE",
  DOWNLOAD_DELETE: "DOWNLOAD_DELETE",
  DOWNLOAD_RESTORE: "DOWNLOAD_RESTORE",

  MEDIA_UPLOAD: "MEDIA_UPLOAD",
  MEDIA_UPDATE: "MEDIA_UPDATE",
  MEDIA_DELETE: "MEDIA_DELETE",
  MEDIA_RESTORE: "MEDIA_RESTORE",

  MESSAGE_UPDATE: "MESSAGE_UPDATE",
  MESSAGE_DELETE: "MESSAGE_DELETE",
  MESSAGE_RESTORE: "MESSAGE_RESTORE",

  TRASH_RESTORE: "TRASH_RESTORE",
  TRASH_DELETE_PERMANENTLY: "TRASH_DELETE_PERMANENTLY",
});

export const AUDIT_ENTITY_TYPES = Object.freeze({
  AUTH: "auth",
  USER: "user",
  SITE_SETTINGS: "siteSettings",
  PAGE: "page",
  CATEGORY: "category",
  PRODUCT: "product",
  SOLUTION: "solution",
  PROJECT: "project",
  STANDARD: "standard",
  DOWNLOAD: "download",
  MEDIA: "media",
  MESSAGE: "message",
  TRASH: "trash",
});

export const AUDIT_ACTION_VALUES = Object.freeze(Object.values(AUDIT_ACTIONS));

export const AUDIT_ENTITY_TYPE_VALUES = Object.freeze(
  Object.values(AUDIT_ENTITY_TYPES),
);
