export const productCategories = [
  {
    id: "door-closers",
    slug: "door-closers",
    translationKey: "doorClosers",
    image: "/images/products/categories/door-closers.jpg",
    icon: "doorCloser",
    featured: true,
  },
  {
    id: "lever-handles",
    slug: "lever-handles",
    translationKey: "leverHandles",
    image: "/images/products/categories/lever-handles.jpg",
    icon: "leverHandle",
    featured: false,
  },
  {
    id: "locks-cylinders",
    slug: "locks-cylinders",
    translationKey: "locksCylinders",
    image: "/images/products/categories/locks-cylinders.jpg",
    icon: "lock",
    featured: false,
  },
  {
    id: "hinges",
    slug: "hinges",
    translationKey: "hinges",
    image: "/images/products/categories/hinges.jpg",
    icon: "hinge",
    featured: false,
  },
  {
    id: "panic-exit-hardware",
    slug: "panic-exit-hardware",
    translationKey: "panicExitHardware",
    image: "/images/products/categories/panic-exit-hardware.jpg",
    icon: "exit",
    featured: false,
  },
  {
    id: "door-window-seals",
    slug: "door-window-seals",
    translationKey: "doorWindowSeals",
    image: "/images/products/categories/door-window-seals.jpg",
    icon: "seal",
    featured: false,
  },
  {
    id: "fire-doors",
    slug: "fire-doors",
    translationKey: "fireDoors",
    image: "/images/products/categories/fire-doors.jpg",
    icon: "fire",
    featured: false,
  },
  {
    id: "electronic-locks",
    slug: "electronic-locks",
    translationKey: "electronicLocks",
    image: "/images/products/categories/electronic-locks.jpg",
    icon: "electronicLock",
    featured: false,
  },
];
